import { Provider } from '@angular/core';
import { provideNzConfig } from 'ng-zorro-antd/core/config';
import { provideNzIcons } from 'ng-zorro-antd/icon';
import { NZ_I18N, ro_RO } from 'ng-zorro-antd/i18n';
import { IconDefinition } from '@ant-design/icons-angular';
import {
  ArrowLeftOutline,
  CopyOutline,
  MailOutline,
  PhoneOutline,
  UserOutline,
  WarningOutline,
  LoadingOutline,
  CheckCircleOutline,
  CloseCircleOutline,
  InfoCircleOutline,
  ExclamationCircleOutline,
  PlusOutline,
  SearchOutline,
  FilterOutline,
  EnvironmentOutline,
  CalendarOutline,
  ClockCircleOutline,
  ShareAltOutline,
  FacebookOutline,
  TwitterOutline,
  LinkedinOutline,
  LinkOutline,
  ZoomInOutline,
  PictureOutline,
  SendOutline,
  BankOutline,
  SafetyCertificateOutline,
  ApartmentOutline,
  TeamOutline,
  GlobalOutline,
  CompassOutline,
  ForwardOutline,
  HomeOutline,
  ReloadOutline,
  FileExclamationOutline,
  LeftOutline,
  RightOutline,
  EyeOutline,
  ArrowRightOutline,
  GoogleOutline,
  EyeInvisibleOutline,
  PlusCircleOutline,
  FileTextOutline,
  UserAddOutline,
  LoginOutline,
  LogoutOutline,
  DownOutline,
  SettingOutline,
  NotificationOutline,
  HeartOutline,
  LikeOutline,
  ToolOutline,
  MessageOutline,
  RobotOutline,
  UploadOutline,
  CameraOutline,
  DeleteOutline,
  EditOutline,
  CheckOutline,
  PercentageOutline,
  FieldTimeOutline,
  FlagOutline,
  InboxOutline,
  TrophyOutline,
  CrownOutline,
  StarOutline,
  FireOutline,
  // Admin panel icons
  DashboardOutline,
  HistoryOutline,
  AuditOutline,
  FileAddOutline,
  CheckSquareOutline,
  CaretDownFill,
  UnorderedListOutline
} from '@ant-design/icons-angular/icons';

// The `theme` field was removed: it triggered NG-ZORRO's runtime CSS-variable
// injection (`NzConfigService: SSR do not support dynamic theme with css
// variables.`), which does nothing on the server and then causes a visible
// flash during hydration on the client. All of these colors are already baked
// into the compiled CSS by `src/theme.less` (which imports the NG-ZORRO LESS
// theme and overrides its variables), so the runtime config was redundant.
export const ngZorroConfig = provideNzConfig({
  message: {
    nzTop: 24,
    nzDuration: 3000,
    nzMaxStack: 3,
  },
  notification: {
    nzTop: '24px',
    nzPlacement: 'topRight',
  }
});

const icons: IconDefinition[] = [
  ArrowLeftOutline,
  CopyOutline,
  MailOutline,
  PhoneOutline,
  UserOutline,
  WarningOutline,
  LoadingOutline,
  CheckCircleOutline,
  CloseCircleOutline,
  InfoCircleOutline,
  ExclamationCircleOutline,
  PlusOutline,
  SearchOutline,
  FilterOutline,
  EnvironmentOutline,
  CalendarOutline,
  ClockCircleOutline,
  ShareAltOutline,
  FacebookOutline,
  TwitterOutline,
  LinkedinOutline,
  LinkOutline,
  ZoomInOutline,
  PictureOutline,
  SendOutline,
  BankOutline,
  SafetyCertificateOutline,
  ApartmentOutline,
  TeamOutline,
  GlobalOutline,
  CompassOutline,
  ForwardOutline,
  HomeOutline,
  ReloadOutline,
  FileExclamationOutline,
  LeftOutline,
  RightOutline,
  EyeOutline,
  ArrowRightOutline,
  GoogleOutline,
  EyeInvisibleOutline,
  PlusCircleOutline,
  FileTextOutline,
  UserAddOutline,
  LoginOutline,
  LogoutOutline,
  DownOutline,
  SettingOutline,
  NotificationOutline,
  HeartOutline,
  LikeOutline,
  ToolOutline,
  MessageOutline,
  RobotOutline,
  UploadOutline,
  CameraOutline,
  DeleteOutline,
  EditOutline,
  CheckOutline,
  PercentageOutline,
  FieldTimeOutline,
  FlagOutline,
  InboxOutline,
  TrophyOutline,
  CrownOutline,
  StarOutline,
  FireOutline,
  // Admin panel icons
  DashboardOutline,
  HistoryOutline,
  AuditOutline,
  FileAddOutline,
  CheckSquareOutline,
  CaretDownFill,
  UnorderedListOutline
];

export const ngZorroIcons = provideNzIcons(icons);

export const ngZorroI18n: Provider = { provide: NZ_I18N, useValue: ro_RO };