const fs = require('fs');
const path = require('path');
const matter = require('gray-matter');
const { marked } = require('marked');

const CONTENT_DIR = path.join(__dirname, '..', 'src', 'content', 'guides');
const PUBLIC_DIR = path.join(__dirname, '..', 'public');
const OUTPUT_FILE = path.join(__dirname, '..', 'src', 'app', 'generated', 'guide-data.ts');

const ARTICLE_INTERFACE = `export interface GuideArticle {
  slug: string;
  title: string;
  description: string;
  category: string;
  publishedAt: string;
  readingTime: string;
  featured: boolean;
  image: string;
  /** Intrinsic size of \`image\`, measured at build time. Absent if unreadable. */
  imageWidth?: number;
  imageHeight?: number;
  imageType?: string;
  htmlContent: string;
}`;

// Configure marked for clean HTML output
marked.use({
  gfm: true,
  breaks: false,
});

function pngSize(buffer) {
  if (buffer.length < 24 || buffer.toString('ascii', 1, 4) !== 'PNG') return null;
  return {
    imageWidth: buffer.readUInt32BE(16),
    imageHeight: buffer.readUInt32BE(20),
    imageType: 'image/png',
  };
}

function jpegSize(buffer) {
  if (buffer.length < 4 || buffer.readUInt16BE(0) !== 0xffd8) return null;

  let offset = 2;
  while (offset + 9 < buffer.length) {
    if (buffer[offset] !== 0xff) {
      offset++;
      continue;
    }
    const marker = buffer[offset + 1];
    // Standalone markers carry no length field.
    if (marker === 0x01 || (marker >= 0xd0 && marker <= 0xd9)) {
      offset += 2;
      continue;
    }
    // Start-of-frame, excluding the huffman/arithmetic/restart tables that
    // share the 0xc0-0xcf range.
    if (marker >= 0xc0 && marker <= 0xcf && marker !== 0xc4 && marker !== 0xc8 && marker !== 0xcc) {
      return {
        imageHeight: buffer.readUInt16BE(offset + 5),
        imageWidth: buffer.readUInt16BE(offset + 7),
        imageType: 'image/jpeg',
      };
    }
    offset += 2 + buffer.readUInt16BE(offset + 2);
  }
  return null;
}

/**
 * Reads the intrinsic size straight from the file header so `og:image:width`
 * and `og:image:height` can be declared for guide share cards — those hints are
 * what makes Facebook and LinkedIn draw the image on the first share instead of
 * a text-only card. Hardcoding them in the component would drift the moment an
 * illustration is re-exported, so anything unmeasurable yields no hint at all
 * rather than a guess.
 */
function measureImage(relativePath) {
  if (!relativePath) return {};

  const file = path.join(PUBLIC_DIR, relativePath.replace(/^\/+/, ''));
  let buffer;
  try {
    buffer = fs.readFileSync(file);
  } catch {
    console.warn(`[build-guides] Cannot read ${relativePath} — social card will omit dimensions`);
    return {};
  }

  const size = pngSize(buffer) || jpegSize(buffer);
  if (!size) {
    console.warn(`[build-guides] Unrecognised image format ${relativePath} — social card will omit dimensions`);
    return {};
  }
  return size;
}

function buildGuides() {
  const outputDir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  if (!fs.existsSync(CONTENT_DIR)) {
    console.warn('[build-guides] No content directory found at', CONTENT_DIR);
    fs.writeFileSync(
      OUTPUT_FILE,
      `// AUTO-GENERATED — DO NOT EDIT\n\n${ARTICLE_INTERFACE}\n\nexport const GUIDE_ARTICLES: GuideArticle[] = [];\n`,
    );
    return;
  }

  const files = fs.readdirSync(CONTENT_DIR).filter(f => f.endsWith('.md'));

  const articles = files.map(file => {
    const raw = fs.readFileSync(path.join(CONTENT_DIR, file), 'utf-8');
    const { data, content } = matter(raw);
    const htmlContent = marked.parse(content);

    // Estimate reading time (~200 words/min for Romanian)
    const wordCount = content.split(/\s+/).filter(Boolean).length;
    const readingTime = `${Math.max(1, Math.ceil(wordCount / 200))} min citire`;
    const image = data.image || '';

    return {
      slug: data.slug || file.replace('.md', ''),
      title: data.title || 'Untitled',
      description: data.description || '',
      category: data.category || 'general',
      publishedAt: data.publishedAt || new Date().toISOString().split('T')[0],
      readingTime,
      featured: data.featured || false,
      image,
      ...measureImage(image),
      htmlContent,
    };
  });

  // Sort: featured first, then by date descending
  articles.sort((a, b) => {
    if (a.featured !== b.featured) return b.featured ? 1 : -1;
    return b.publishedAt.localeCompare(a.publishedAt);
  });

  const output = `// AUTO-GENERATED by scripts/build-guides.js — DO NOT EDIT
// Source: src/content/guides/*.md

${ARTICLE_INTERFACE}

export const GUIDE_ARTICLES: GuideArticle[] = ${JSON.stringify(articles, null, 2)};
`;

  fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');
  console.log(`[build-guides] Generated ${articles.length} articles → ${OUTPUT_FILE}`);
}

buildGuides();
